#Requires -Version 5.1
<#
.SYNOPSIS
    Applies config.json: writes config.js for the browser and updates the sync task interval.

.DESCRIPTION
    Edit config.json (or use settings.html), then run this script on the display PC.

    - Writes config.js (loaded by slideshow.html from file://)
    - If the DisplayBoard-Sync scheduled task exists, updates its repetition interval
    - Does not require admin unless the task was registered by another user

.EXAMPLE
    .\Apply-Config.ps1
.EXAMPLE
    .\Apply-Config.ps1 -ConfigPath .\config.json -TriggerSync
#>
[CmdletBinding()]
param(
    [string]$ConfigPath = (Join-Path $PSScriptRoot 'config.json'),
    [switch]$TriggerSync
)

function Read-DisplayConfig {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Config not found: $Path"
    }
    $raw = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
    $cfg = $raw | ConvertFrom-Json
    if (-not $cfg.sourcePath) {
        throw "config.json is missing required field: sourcePath"
    }
    [pscustomobject]@{
        SourcePath          = [string]$cfg.sourcePath
        LocalPath           = if ($cfg.localPath) { [string]$cfg.localPath } else { 'images' }
        SyncIntervalMinutes = if ($cfg.syncIntervalMinutes) { [int]$cfg.syncIntervalMinutes } else { 15 }
        PollMinutes         = if ($cfg.pollMinutes) { [int]$cfg.pollMinutes } else { 5 }
        SlideSeconds        = if ($cfg.slideSeconds) { [int]$cfg.slideSeconds } else { 8 }
        Extensions          = if ($cfg.extensions) { @($cfg.extensions) } else {
            @('.jpg','.jpeg','.png','.gif','.bmp','.webp')
        }
    }
}

function Write-ConfigJs {
    param($Cfg, [string]$OutPath)
    $extJson = ($Cfg.Extensions | ForEach-Object { "'$_'" }) -join ', '
    $src = ($Cfg.SourcePath -replace '\\', '\\' -replace "'", "\'")
    $local = ($Cfg.LocalPath -replace '\\', '\\' -replace "'", "\'")
    $content = @"
// AUTO-GENERATED by Apply-Config.ps1 / SlideshowSync.ps1 -- edit config.json instead.
window.SLIDESHOW_CONFIG = {
  sourcePath: '$src',
  localPath: '$local',
  syncIntervalMinutes: $($Cfg.SyncIntervalMinutes),
  pollMinutes: $($Cfg.PollMinutes),
  slideSeconds: $($Cfg.SlideSeconds),
  extensions: [$extJson]
};
"@
    Set-Content -LiteralPath $OutPath -Value $content -Encoding UTF8
}

$cfg = Read-DisplayConfig -Path $ConfigPath
$configJs = Join-Path $PSScriptRoot 'config.js'
Write-ConfigJs -Cfg $cfg -OutPath $configJs
Write-Host "Wrote $configJs" -ForegroundColor Green
Write-Host "  sourcePath          = $($cfg.SourcePath)"
Write-Host "  syncIntervalMinutes = $($cfg.SyncIntervalMinutes)"
Write-Host "  pollMinutes         = $($cfg.PollMinutes)"
Write-Host "  slideSeconds        = $($cfg.SlideSeconds)"

$taskName = 'DisplayBoard-Sync'
$task = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
if ($task) {
    $syncScript = Join-Path $PSScriptRoot 'SlideshowSync.ps1'
    $action = New-ScheduledTaskAction -Execute 'powershell.exe' `
        -Argument ('-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File "{0}"' -f $syncScript)

    $atLogon = New-ScheduledTaskTrigger -AtLogOn
    $repeating = New-ScheduledTaskTrigger -Once -At (Get-Date).Date `
        -RepetitionInterval (New-TimeSpan -Minutes $cfg.SyncIntervalMinutes) `
        -RepetitionDuration ([TimeSpan]::FromDays(3650))

    $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
        -StartWhenAvailable -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Minutes 30)

    $principal = $task.Principal
    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $atLogon, $repeating `
        -Principal $principal -Settings $settings -Force | Out-Null
    Write-Host "Updated scheduled task '$taskName' to every $($cfg.SyncIntervalMinutes) minute(s)." -ForegroundColor Green
} else {
    Write-Host "Scheduled task '$taskName' not found. Run Install-DisplayBoard.ps1 after setting sourcePath." -ForegroundColor Yellow
}

if ($TriggerSync) {
    $sync = Join-Path $PSScriptRoot 'SlideshowSync.ps1'
    if (Test-Path $sync) {
        Write-Host 'Running sync once...' -ForegroundColor Cyan
        & $sync
    }
}
